Repository ros-controls/ros2_controllers, pull requests merged in 2023-12, with the labels that each got.

#842 [JTC] Continue with last trajectory-point on success
  joint_trajectory_controller/doc/userdoc.rst
  joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_actions.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-iron

#434 🚀 Add PID controller 🎉
  doc/controllers_index.rst
  pid_controller/CMakeLists.txt
  pid_controller/README.md
  pid_controller/doc/userdoc.rst
  pid_controller/include/pid_controller/pid_controller.hpp
  pid_controller/include/pid_controller/visibility_control.h
  pid_controller/package.xml
  pid_controller/pid_controller.xml
  pid_controller/src/pid_controller.cpp
  pid_controller/src/pid_controller.yaml
  pid_controller/test/pid_controller_params.yaml
  pid_controller/test/pid_controller_preceding_params.yaml
  pid_controller/test/test_load_pid_controller.cpp
  pid_controller/test/test_pid_controller.cpp
  pid_controller/test/test_pid_controller.hpp
  pid_controller/test/test_pid_controller_preceding.cpp
  ros2_controllers/package.xml
Labels: enhancement

#879 Fix floating point comparison in JTC
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
Labels: backport-iron

#890 Fix rqt jtc bugs for continuous joints and other minor bugs
  rqt_joint_trajectory_controller/rqt_joint_trajectory_controller/joint_limits_urdf.py
  rqt_joint_trajectory_controller/rqt_joint_trajectory_controller/joint_trajectory_controller.py
Labels: backport-iron

#927 Changing default int values to double in steering controller's yaml file
  steering_controllers_library/src/steering_controllers_library.yaml
Labels: backport-humble, backport-iron

#932 [JTC] Add console output for tolerance checks
  joint_trajectory_controller/include/joint_trajectory_controller/tolerances.hpp
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
Labels: backport-humble, backport-iron

#946 [CI] Do not run reviewer lottery for dependabot and mergify
  .github/workflows/reviewer_lottery.yml
Labels: backport-humble, backport-iron

#950 Add rqt_JTC to docs
  joint_trajectory_controller/doc/userdoc.rst
  rqt_joint_trajectory_controller/doc/rqt_joint_trajectory_controller.png
  rqt_joint_trajectory_controller/doc/userdoc.rst
Labels: backport-humble, backport-iron

#921 Fix ackermann steering odometry
  steering_controllers_library/CMakeLists.txt
  steering_controllers_library/src/steering_odometry.cpp
  steering_controllers_library/test/test_steering_odometry.cpp
Labels: backport-humble, backport-iron
