Repository ros-controls/ros2_controllers, pull requests merged in 2023-11, with the labels that each got.

#812 [diff_drive_controller] Remove non-stamped Twist option
  diff_drive_controller/doc/userdoc.rst
  diff_drive_controller/include/diff_drive_controller/diff_drive_controller.hpp
  diff_drive_controller/src/diff_drive_controller.cpp
  diff_drive_controller/src/diff_drive_controller_parameter.yaml
Labels: hold

#822 [diff_drive_controller] Fixed typos in diff_drive_controller_paramete…
  diff_drive_controller/src/diff_drive_controller_parameter.yaml
Labels: backport-humble, backport-iron

#797 [JTC] Fix state offset tests
  joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-iron

#761 [JTC] Activate update of dynamic parameters
  joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-iron

#846 [docs] Resort overview page
  README.md
  doc/controllers_index.rst
  forward_command_controller/doc/userdoc.rst
Labels: backport-humble, backport-iron

#845 [JTC] Remove unused home pose
  joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
Labels: backport-humble, backport-iron

#849 [JTC] Fix dynamic reconfigure of tolerances
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-iron

#858 [JTC] Improve update methods for tests
  joint_trajectory_controller/test/test_trajectory_actions.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-iron

#859 joint_state_broadcaster: Add proper subscription to TestCustomInterfaceMappingUpdate
  joint_state_broadcaster/test/test_joint_state_broadcaster.cpp
  joint_state_broadcaster/test/test_joint_state_broadcaster.hpp
Labels: backport-humble, backport-iron

#856 Increase test coverage
  force_torque_sensor_broadcaster/test/test_force_torque_sensor_broadcaster.cpp
  force_torque_sensor_broadcaster/test/test_force_torque_sensor_broadcaster.hpp
  forward_command_controller/test/test_forward_command_controller.cpp
  forward_command_controller/test/test_multi_interface_forward_command_controller.cpp
  gripper_controllers/test/test_gripper_controllers.cpp
  imu_sensor_broadcaster/test/test_imu_sensor_broadcaster.cpp
  joint_state_broadcaster/test/test_joint_state_broadcaster.cpp
  joint_state_broadcaster/test/test_joint_state_broadcaster.hpp
  range_sensor_broadcaster/test/test_range_sensor_broadcaster.cpp
  tricycle_controller/test/test_tricycle_controller.cpp
Labels: backport-humble, backport-iron

#857 [JTC] Activate checks for parameter validation
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-humble, backport-iron
