Repository ros-controls/ros2_controllers, pull requests merged in 2024-11, with the labels that each got.

#1331 [JSB] Fix the behaviour of publishing unavailable state interfaces when they are previously available
  joint_state_broadcaster/src/joint_state_broadcaster.cpp
  joint_state_broadcaster/test/test_joint_state_broadcaster.cpp
  joint_state_broadcaster/test/test_joint_state_broadcaster.hpp
Labels: backport-humble, backport-iron

#1247 Adding use of robot description parameter in the Admittance Controller
  admittance_controller/include/admittance_controller/admittance_rule.hpp
  admittance_controller/include/admittance_controller/admittance_rule_impl.hpp
  admittance_controller/src/admittance_controller.cpp
  admittance_controller/test/test_admittance_controller.hpp
Labels: backport-iron

#1360 [JTC] Fix the JTC length_error exceptions in the tests
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-humble, backport-iron

#1363 Update maintainers and add url tags
  ackermann_steering_controller/package.xml
  admittance_controller/package.xml
  bicycle_steering_controller/package.xml
  diff_drive_controller/package.xml
  effort_controllers/package.xml
  force_torque_sensor_broadcaster/package.xml
  forward_command_controller/package.xml
  gripper_controllers/package.xml
  imu_sensor_broadcaster/package.xml
  joint_state_broadcaster/package.xml
  joint_trajectory_controller/package.xml
  parallel_gripper_controller/package.xml
  pid_controller/package.xml
  pose_broadcaster/package.xml
  position_controllers/package.xml
  range_sensor_broadcaster/package.xml
  ros2_controllers/package.xml
  ros2_controllers_test_nodes/package.xml
  rqt_joint_trajectory_controller/package.xml
  steering_controllers_library/package.xml
  tricycle_controller/package.xml
  tricycle_steering_controller/package.xml
  velocity_controllers/package.xml
Labels: backport-humble, backport-iron

#1341 TractionLimiter: Fix wrong input checks
  tricycle_controller/CMakeLists.txt
  tricycle_controller/include/tricycle_controller/traction_limiter.hpp
  tricycle_controller/src/traction_limiter.cpp
  tricycle_controller/test/test_traction_limiter.cpp
Labels: backport-humble, backport-iron

#1369 test_nodes: catch keyboard interrupt and add simple launch tests
  ros2_controllers_test_nodes/ros2_controllers_test_nodes/publisher_forward_position_controller.py
  ros2_controllers_test_nodes/ros2_controllers_test_nodes/publisher_joint_trajectory_controller.py
  ros2_controllers_test_nodes/setup.py
  ros2_controllers_test_nodes/test/rrbot_forward_position_publisher.yaml
  ros2_controllers_test_nodes/test/rrbot_joint_trajectory_publisher.yaml
  ros2_controllers_test_nodes/test/test_publisher_forward_position_controller_launch.py
  ros2_controllers_test_nodes/test/test_publisher_joint_trajectory_controller_launch.py
Labels: backport-humble

#1251 Gpio command controller
  doc/controllers_index.rst
  doc/release_notes.rst
  gpio_controllers/CMakeLists.txt
  gpio_controllers/doc/userdoc.rst
  gpio_controllers/gpio_controllers_plugin.xml
  gpio_controllers/include/gpio_controllers/gpio_command_controller.hpp
  gpio_controllers/include/gpio_controllers/visibility_control.h
  gpio_controllers/package.xml
  gpio_controllers/src/gpio_command_controller.cpp
  gpio_controllers/src/gpio_command_controller_parameters.yaml
  gpio_controllers/test/test_gpio_command_controller.cpp
  gpio_controllers/test/test_load_gpio_command_controller.cpp
  ros2_controllers/package.xml
Labels: backport-humble

#1338 Remove iron workflows and update readme
  .github/dependabot.yml
  .github/mergify.yml
  .github/workflows/iron-abi-compatibility.yml
  .github/workflows/iron-binary-build.yml
  .github/workflows/iron-check-docs.yml
  .github/workflows/iron-coverage-build.yml
  .github/workflows/iron-debian-build.yml
  .github/workflows/iron-pre-commit.yml
  .github/workflows/iron-rhel-semi-binary-build.yml
  .github/workflows/iron-semi-binary-build.yml
  .github/workflows/iron-source-build.yml
  README.md
  ros2_controllers-not-released.iron.repos
  ros2_controllers.iron.repos
Labels: backport-humble

#512 Add Mecanum Drive Controller
  doc/controllers_index.rst
  doc/release_notes.rst
  mecanum_drive_controller/CMakeLists.txt
  mecanum_drive_controller/doc/userdoc.rst
  mecanum_drive_controller/include/mecanum_drive_controller/mecanum_drive_controller.hpp
  mecanum_drive_controller/include/mecanum_drive_controller/odometry.hpp
  mecanum_drive_controller/include/mecanum_drive_controller/visibility_control.h
  mecanum_drive_controller/mecanum_drive_controller.xml
  mecanum_drive_controller/package.xml
  mecanum_drive_controller/src/mecanum_drive_controller.cpp
  mecanum_drive_controller/src/mecanum_drive_controller.yaml
  mecanum_drive_controller/src/odometry.cpp
  mecanum_drive_controller/test/mecanum_drive_controller_params.yaml
  mecanum_drive_controller/test/mecanum_drive_controller_preceeding_params.yaml
  mecanum_drive_controller/test/test_load_mecanum_drive_controller.cpp
  mecanum_drive_controller/test/test_mecanum_drive_controller.cpp
  mecanum_drive_controller/test/test_mecanum_drive_controller.hpp
  mecanum_drive_controller/test/test_mecanum_drive_controller_preceeding.cpp
  ros2_controllers/package.xml
  steering_controllers_library/doc/userdoc.rst
Labels: backport-humble, backport-iron

#1378 Add missing deps for test_nodes
  ros2_controllers_test_nodes/package.xml
  ros2_controllers_test_nodes/test/test_publisher_forward_position_controller_launch.py
  ros2_controllers_test_nodes/test/test_publisher_joint_trajectory_controller_launch.py
Labels: backport-humble
