Repository ros-controls/ros2_controllers, pull requests merged in 2024-01, with the labels that each got.

#943 [JTC] Cleanup includes
  joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp
  joint_trajectory_controller/include/joint_trajectory_controller/tolerances.hpp
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller_utils.hpp
Labels: backport-humble, backport-iron

#967 [JTC] Remove read_only from 'joints', 'state_interfaces' and 'command…
  joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml
Labels: backport-humble, backport-iron

#962 [JTC] Cancel active goal in on_deactivate
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
Labels: backport-humble, backport-iron

#978 Revert "[JTC] Remove read_only from 'joints', 'state_interfaces' and 'command_interfaces' parameters (#967)"
  joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml
Labels: backport-humble, backport-iron

#957 [tricycle_controller] Use generate_parameter_library
  tricycle_controller/CMakeLists.txt
  tricycle_controller/doc/userdoc.rst
  tricycle_controller/include/tricycle_controller/tricycle_controller.hpp
  tricycle_controller/package.xml
  tricycle_controller/src/tricycle_controller.cpp
  tricycle_controller/src/tricycle_controller_parameter.yaml
  tricycle_controller/test/test_load_tricycle_controller.cpp
  tricycle_controller/test/test_tricycle_controller.cpp
Labels: backport-humble, backport-iron

#902 [JTC] Invalidate empty trajectory messages
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
Labels: bug, backport-humble, backport-iron

#652 Let sphinx add parameter description with nested structures to documentation
  admittance_controller/doc/userdoc.rst
  diff_drive_controller/doc/parameters_context.yaml
  diff_drive_controller/doc/userdoc.rst
  force_torque_sensor_broadcaster/doc/parameters_context.yaml
  force_torque_sensor_broadcaster/doc/userdoc.rst
  force_torque_sensor_broadcaster/src/force_torque_sensor_broadcaster_parameters.yaml
  gripper_controllers/doc/userdoc.rst
  imu_sensor_broadcaster/doc/userdoc.rst
  joint_state_broadcaster/doc/joint_state_broadcaster_parameter_context.yml
  joint_state_broadcaster/doc/userdoc.rst
  joint_state_broadcaster/src/joint_state_broadcaster_parameters.yaml
  joint_trajectory_controller/doc/parameters.rst
  joint_trajectory_controller/doc/parameters_context.yaml
  joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml
  range_sensor_broadcaster/doc/userdoc.rst
Labels: backport-humble, backport-iron

#899 Add tests for `interface_configuration_type` consistently
  ackermann_steering_controller/test/test_ackermann_steering_controller.cpp
  ackermann_steering_controller/test/test_ackermann_steering_controller.hpp
  ackermann_steering_controller/test/test_ackermann_steering_controller_preceeding.cpp
  admittance_controller/test/test_admittance_controller.cpp
  bicycle_steering_controller/test/test_bicycle_steering_controller.cpp
  bicycle_steering_controller/test/test_bicycle_steering_controller.hpp
  bicycle_steering_controller/test/test_bicycle_steering_controller_preceeding.cpp
  diff_drive_controller/test/test_diff_drive_controller.cpp
  force_torque_sensor_broadcaster/test/test_force_torque_sensor_broadcaster.cpp
  forward_command_controller/test/test_forward_command_controller.cpp
  forward_command_controller/test/test_multi_interface_forward_command_controller.cpp
  imu_sensor_broadcaster/test/test_imu_sensor_broadcaster.cpp
  joint_state_broadcaster/test/test_joint_state_broadcaster.cpp
  joint_trajectory_controller/test/test_trajectory_controller.cpp
  pid_controller/test/test_pid_controller.cpp
  pid_controller/test/test_pid_controller_preceding.cpp
  range_sensor_broadcaster/test/test_range_sensor_broadcaster.cpp
  steering_controllers_library/test/test_steering_controllers_library.cpp
  steering_controllers_library/test/test_steering_controllers_library.hpp
  tricycle_steering_controller/test/test_tricycle_steering_controller.cpp
  tricycle_steering_controller/test/test_tricycle_steering_controller.hpp
  tricycle_steering_controller/test/test_tricycle_steering_controller_preceeding.cpp
Labels: backport-iron

#887 [JTC] Fill action error_strings
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
Labels: enhancement, backport-humble, backport-iron
