Repository ros-controls/ros2_controllers, pull requests merged in 2025-06, with the labels that each got.

#1685 Remove deprecated parameter from pose_broadcaster
  pose_broadcaster/include/pose_broadcaster/pose_broadcaster.hpp
  pose_broadcaster/src/pose_broadcaster.cpp
  pose_broadcaster/src/pose_broadcaster_parameters.yaml
Labels: hold

#1743 Set enable_feedforward parameter in the respective tests
  pid_controller/test/test_pid_controller.cpp
  pid_controller/test/test_pid_controller_dual_interface.cpp
Labels: backport-jazzy

#1748 [JTC Doc] Update PID documentation for effort related command interface support
  joint_trajectory_controller/doc/parameters_context.yaml
  joint_trajectory_controller/doc/userdoc.rst
Labels: backport-jazzy

#1759 Add new AntiWindup parameters to JTC
  doc/release_notes.rst
  joint_trajectory_controller/src/joint_trajectory_controller.cpp
  joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml
Labels: backport-jazzy

#1749 Fix atomic variables in JTC
  joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp
Labels: backport-humble, backport-jazzy

#1777 Fix SteeringOdometry calculation error
  steering_controllers_library/src/steering_odometry.cpp
Labels: backport-humble, backport-jazzy
