Repository ros-controls/ros2_controllers, pull requests merged in 2025-05, with the labels that each got.

#1652 Remove deprecated gripper_controller
  doc/controllers_index.rst
  doc/migration.rst
  gripper_controllers/CHANGELOG.rst
  gripper_controllers/CMakeLists.txt
  gripper_controllers/doc/userdoc.rst
  gripper_controllers/include/gripper_controllers/gripper_action_controller.hpp
  gripper_controllers/include/gripper_controllers/gripper_action_controller_impl.hpp
  gripper_controllers/include/gripper_controllers/hardware_interface_adapter.hpp
  gripper_controllers/package.xml
  gripper_controllers/ros_control_plugins.xml
  gripper_controllers/src/gripper_action_controller.cpp
  gripper_controllers/src/gripper_action_controller_parameters.yaml
  gripper_controllers/test/test_gripper_controllers.cpp
  gripper_controllers/test/test_gripper_controllers.hpp
  gripper_controllers/test/test_load_gripper_action_controllers.cpp
  ros2_controllers/package.xml
Labels: hold

#1564 fixed on_set_chained_mode implementations to avoid cpplint warnings
  diff_drive_controller/src/diff_drive_controller.cpp
  mecanum_drive_controller/src/mecanum_drive_controller.cpp
  pid_controller/src/pid_controller.cpp
  steering_controllers_library/src/steering_controllers_library.cpp
Labels: backport-humble, backport-jazzy

#1553 Add enable_feedforward parameter
  pid_controller/doc/userdoc.rst
  pid_controller/include/pid_controller/pid_controller.hpp
  pid_controller/src/pid_controller.cpp
  pid_controller/src/pid_controller.yaml
  pid_controller/test/test_pid_controller.cpp
  pid_controller/test/test_pid_controller.hpp
  pid_controller/test/test_pid_controller_dual_interface.cpp
  pid_controller/test/test_pid_controller_preceding.cpp
Labels: backport-jazzy

#1690 Use `warning` attribute of RcutilsLogger
  ros2_controllers_test_nodes/ros2_controllers_test_nodes/publisher_joint_trajectory_controller.py
Labels: backport-jazzy

#1701 Cleanup and grooming of CI
  .github/workflows/humble-binary-build.yml
  .github/workflows/humble-debian-build.yml
  .github/workflows/humble-rhel-semi-binary-build.yml
  .github/workflows/humble-semi-binary-build.yml
  .github/workflows/humble-source-build.yml
  .github/workflows/jazzy-binary-build.yml
  .github/workflows/jazzy-debian-build.yml
  .github/workflows/jazzy-rhel-semi-binary-build.yml
  .github/workflows/jazzy-semi-binary-build.yml
  .github/workflows/jazzy-source-build.yml
  .github/workflows/prerelease-check.yml
  .github/workflows/rolling-binary-build.yml
  .github/workflows/rolling-debian-build.yml
  .github/workflows/rolling-rhel-semi-binary-build.yml
  .github/workflows/rolling-semi-binary-build.yml
  .github/workflows/rolling-source-build.yml
Labels: backport-humble, backport-jazzy

#1704 Remove CMAKE_CXX_STANDARD
  range_sensor_broadcaster/CMakeLists.txt
Labels: backport-jazzy
